import type { NextPage } from 'next'
import { useTranslation } from 'next-i18next'
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { AppBar, IconButton, Toolbar, Typography } from '@mui/material'
import MenuIcon from '@mui/icons-material/Menu'

interface Props {
  data: any
}

const Home: NextPage<Props> = ({ data }) => {
  const { t } = useTranslation()

  console.log(data)

  return (
    <div>
      <Head>
        <title>CAS - {data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="static" color="primary" style={{ backgroundColor: data.theme.primaryColor }}>
        <Toolbar>
          <IconButton edge="start" color="inherit" aria-label="menu">
            <MenuIcon />
          </IconButton>
          <Typography variant="h6" color="inherit">
            {t('casLong')}
          </Typography>
        </Toolbar>
      </AppBar>
    </div>
  )
}

export default Home

export async function getStaticProps({ locale }: { locale: string }) {
  // Fetch data from external API
  const res = await fetch('https://t1vy4habx7.execute-api.eu-north-1.amazonaws.com/organizations/kommunkoping_v2/info')
  const data = await res.json()

  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
      data,
    },
  }
}
