import type { NextPage } from 'next'
import { useTranslation } from 'next-i18next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { AppBar, Container, IconButton, Toolbar, Typography } from '@mui/material'
import MenuIcon from '@mui/icons-material/Menu';

const Home: NextPage = () => {
  const { t } = useTranslation()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <AppBar position="static" color="primary" style={{ backgroundColor: "#42a5f5"}}>
          <Toolbar>
            <IconButton edge="start" color="inherit" aria-label="menu">
            <MenuIcon />
            </IconButton>
            <Typography variant="h6" color="inherit">{t('casLong')}</Typography>
          </Toolbar>
        </AppBar>
    </div>
  )
}

export default Home

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}